"use client"

import "./globals.css";
import { Inter } from "next/font/google";
// import type { Metadata } from "next";
import Navbar from "./navbar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const disableNavbar = ["/login", "/register"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        {disableNavbar.includes(pathname) ? null : <Navbar/>}
        {children}
      </body>
    </html>
  );
}
